### ISSUE TITLE
WangJieying repo missing essential files

### ISSUE THREAD

**Issue by rmast** [rmast/SDMD-resources#1]
Warning! The WangJieying repo doesn't contain all necessary files.

It points to GeometricTools 5.8, for thrown away files but within the thrown away files some relevant custom edits have been thrown away,

for example BSplineCurveFitterWindow3.cpp contained some custom code BSplineCurveFitterWindow3::SplineFit and BSplineCurveFitterWindow3::SplineFit2 which are still partly reconstructable by https://github.com/WangJieying/Spline/blob/e710c42f96fbead466c4498b05522a27500ecb0f/src/BSplineCurveFitterWindow3.cpp and https://github.com/WangJieying/3S-DMD-resources/blob/9c67744c96835b9da34e53c139a76c54290bc17d/code/3SDMD_code/Code/shared/SplineGenerate/BSplineCurveFitter/BSplineCurveFitterWindow3.cpp

However both of these point to a class BSplineCurveGenerate that has no source in any of these repo's.

Some backups of WangJieying for example might contain #include <Mathematics/BSplineCurveGenerate.h>

If you're able to contact the authors you could try to get it complete or reconstruct the source of BSplineCurveGenerate.

I hope I can reach @WangJieying this way for looking up and adding some customized files that had been thrown away with GeometricTools 5.8.
@AlexTelea

**Comment by WangJieying** [comment]
Thanks for pointing that out. I didn't notice that GeometricTools 5.8 has
been deleted from the original website.
I have already uploaded all the needed libraries.

Thanks again,
Jieying

**Comment by rmast** [comment]
Many thanks!, I can retry my experiment reproducing it with your copy https://github.com/WangJieying/GeometricTools-5.8-library/blob/main/Mathematics/BSplineCurveGenerate.h

However the Git-repo of @davideberly https://github.com/davideberly/GeometricTools/tree/GTE-version-5.8/GTE/Mathematics does not contain this file. Are you sure you didn't make it?

**Comment by davideberly** [comment]
GTE 5.8 does not have a file BSplineCurveGenerate.h. I do not recall ever creating a class named BSplineCurveGenerate. Regarding linking to my zip files at my website, not a good idea. When the current zip file is version major.minor and the next version is major.(minor+1), I delete the older zip file. These days I intend people to grab code from my github repository. Eventually, the website will be revised to store only PDF documentation but have links to github repository.

**Comment by rmast** [comment]
With the new files in separate repo's including https://github.com/WangJieying/GeometricTools-5.8-library I'm finally able to compile. I'll have to rebuild the Azure server to be able to try it.

I'm going to try to somewhat reorder my fork of this repo to make use of the official --recurse-submodules possibility and symbolic links instead of all those additional manual downloads and mixing of custom and external code.

**Comment by rmast** [comment]
I was finally able to find the essential custom files by comparing this version of GTE with the original, see also https://github.com/rmast/GeometricTools-5.8-library/issues/1 

With moving the customized files to the custom directories, specifying -DGTE_USE_LINUX in the makefile and applying the dirty hack of undefining 
```
__gl_h_ __GL_H__ __glext_h_ __GLEXT_H_ 
```
in BSplineCurveFitterWindow3.h I could finally change the dependency of this repo to the dependency of the original GTE-version.
